# podman/docker build -t libredwg-fedora -f Dockerfile-fedora .
ARG BASE_IMAGE=s390x/fedora:32
FROM ${BASE_IMAGE}

# Test with non-root user.
ENV TEST_USER tester
ENV WORK_DIR "/work"

RUN echo -e "deltarpm=0\ninstall_weak_deps=0\ntsflags=nodocs" >> /etc/dnf/dnf.conf
# Disable modular repositories to save a running time of "dnf update"
# if they exists.
RUN ls /etc/yum.repos.d/*.repo
RUN sed -i '/^enabled=1$/ s/1/0/' /etc/yum.repos.d/*-modular.repo || true
RUN yum -y update
RUN yum -y --allowerasing install \
  uname sh bash \
  file gcc git make redhat-rpm-config sudo \
  automake autoconf libtool swig texinfo gcc libxml2 libxml2-devel python3-libxml2 \
  libpcre2-devel libpcre2-32-0 libperl-devel
RUN uname -a

# Create test user and the environment
RUN useradd "${TEST_USER}"
USER "${TEST_USER}"
WORKDIR "${WORK_DIR}"
COPY . .
#RUN chown -R "${TEST_USER}:${TEST_USER}" "${WORK_DIR}"
# Enable sudo without password for convenience.
#RUN echo "${TEST_USER} ALL = NOPASSWD: ALL" >> /etc/sudoers
RUN ./configure --enable-release && \
    make && \
    mkdir -p /${WORK_DIR}/libredwg-install && \
    make check DOCKER=1 DESTDIR="/${WORK_DIR}/libredwg-install" && \
    make install DESTDIR="/${WORK_DIR}/libredwg-install"
